USE [master]
GO
IF DB_ID ('SIACA_INTRANET') IS NOT NULL
DROP DATABASE SIACA_INTRANET;
GO
CREATE DATABASE [SIACA_INTRANET]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = SIACA_INTRANET_DATA, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SIACA_INTRANET_DATA.mdf' , SIZE = 1173760KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = SIACA_INTRANET_LOG, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SIACA_INTRANET_LOG.LDF' , SIZE = 4798144KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO