# Generated by Django 3.0 on 2021-10-01 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_correo', models.CharField(max_length=255, unique=True)),
                ('usu_fecha_modif', models.DateTimeField(auto_now=True)),
                ('usu_estatus', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('usu_usu_modif_fk', models.ForeignKey(blank=True, db_column='usu_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usu_usu_modif_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=255)),
                ('dep_descripcion', models.CharField(max_length=500)),
                ('dep_fecha_modif', models.DateTimeField()),
                ('dep_estatus', models.BooleanField(default=True)),
                ('dep_usu_modif_fk', models.ForeignKey(blank=True, db_column='dep_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_codigo', models.CharField(max_length=255, unique=True)),
                ('per_nombre', models.CharField(max_length=255)),
                ('per_fecha_modif', models.DateTimeField()),
                ('per_estatus', models.BooleanField(default=True)),
                ('per_usu_modif_fk', models.ForeignKey(blank=True, db_column='per_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(max_length=255)),
                ('rol_descripcion', models.CharField(max_length=500)),
                ('rol_fecha_modif', models.DateTimeField()),
                ('rol_estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('rp_id', models.AutoField(primary_key=True, serialize=False)),
                ('rp_fecha_modif', models.DateTimeField()),
                ('rp_estatus', models.BooleanField(default=True)),
                ('rp_per_fk', models.ForeignKey(blank=True, db_column='rp_per_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Permiso')),
                ('rp_rol_fk', models.ForeignKey(blank=True, db_column='rp_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol')),
                ('rp_usu_modif_fk', models.ForeignKey(blank=True, db_column='rp_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rol_Permiso',
                'unique_together': {('rp_rol_fk', 'rp_per_fk')},
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='rol_permisos',
            field=models.ManyToManyField(through='user_login_api.RolPermiso', to='user_login_api.Permiso'),
        ),
        migrations.AddField(
            model_name='rol',
            name='rol_usu_modif_fk',
            field=models.ForeignKey(blank=True, db_column='rol_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=255)),
                ('emp_apellido', models.CharField(max_length=255)),
                ('emp_correo_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_rif', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_ci', models.IntegerField(unique=True)),
                ('emp_fecha_modif', models.DateTimeField()),
                ('emp_estatus', models.BooleanField(default=True)),
                ('emp_dep_fk', models.ForeignKey(blank=True, db_column='emp_dep_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Departamento')),
                ('emp_rol_fk', models.ForeignKey(blank=True, db_column='emp_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol')),
                ('emp_usu_fk', models.ForeignKey(blank=True, db_column='emp_usu_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_usu_fk', to=settings.AUTH_USER_MODEL)),
                ('emp_usu_modif_fk', models.ForeignKey(blank=True, db_column='emp_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_usu_modif_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
    ]
