# Generated by Django 3.0 on 2021-10-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together=set(),
        ),
    ]
