# Generated by Django 3.0 on 2021-10-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0002_auto_20210930_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=255)),
                ('cli_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_correo_personal', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cli_rif', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_ci', models.IntegerField(unique=True)),
                ('cli_fecha_modif', models.DateTimeField()),
                ('cli_estatus', models.BooleanField(default=True)),
                ('cli_rol_fk', models.ForeignKey(blank=True, db_column='cli_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol')),
                ('cli_usu_fk', models.ForeignKey(blank=True, db_column='cli_usu_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cli_usu_fk', to=settings.AUTH_USER_MODEL)),
                ('cli_usu_modif_fk', models.ForeignKey(blank=True, db_column='cli_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cli_usu_modif_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
