# Generated by Django 3.0 on 2021-10-02 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=255)),
                ('pro_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_correo_personal', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pro_rif', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_ci', models.IntegerField(unique=True)),
                ('pro_fecha_modif', models.DateTimeField()),
                ('pro_estatus', models.BooleanField(default=True)),
                ('pro_rol_fk', models.ForeignKey(blank=True, db_column='pro_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol')),
                ('pro_usu_fk', models.ForeignKey(blank=True, db_column='pro_usu_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_usu_fk', to=settings.AUTH_USER_MODEL)),
                ('pro_usu_modif_fk', models.ForeignKey(blank=True, db_column='pro_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_usu_modif_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
    ]
