# Generated by Django 3.0 on 2021-10-02 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('anu_id', models.AutoField(primary_key=True, serialize=False)),
                ('anu_titulo', models.CharField(max_length=255)),
                ('anu_mensaje', models.CharField(max_length=500)),
                ('anu_fecha_modif', models.DateTimeField()),
                ('anu_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Anuncio',
            },
        ),
        migrations.CreateModel(
            name='ArchivoGestionCalidad',
            fields=[
                ('agc_id', models.AutoField(primary_key=True, serialize=False)),
                ('agc_titulo', models.CharField(max_length=255)),
                ('agc_descripcion', models.CharField(max_length=500)),
                ('agc_direccion', models.CharField(max_length=500)),
                ('agc_fecha_modif', models.DateTimeField()),
                ('agc_estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ArchivoGestionCalidad',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoAnuncio',
            fields=[
                ('ea_id', models.AutoField(primary_key=True, serialize=False)),
                ('ea_fecha_enviado', models.DateTimeField()),
                ('ea_fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('ea_visto', models.BooleanField(default=False)),
                ('ea_anu_fk', models.ForeignKey(blank=True, db_column='ea_anu_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Anuncio')),
                ('ea_emp_fk', models.ForeignKey(blank=True, db_column='ea_emp_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Empleado')),
            ],
            options={
                'db_table': 'Empleado_Anuncio',
                'unique_together': {('ea_anu_fk', 'ea_emp_fk')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoServiciosPrestados',
            fields=[
                ('asp_id', models.AutoField(primary_key=True, serialize=False)),
                ('asp_titulo', models.CharField(max_length=255)),
                ('asp_descripcion', models.CharField(max_length=500)),
                ('asp_direccion', models.CharField(max_length=500)),
                ('asp_fecha_modif', models.DateTimeField()),
                ('asp_estatus', models.BooleanField(default=True)),
                ('asp_pro_fk', models.ForeignKey(blank=True, db_column='asp_pro_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Proveedor')),
                ('asp_usu_modif_fk', models.ForeignKey(blank=True, db_column='asp_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArchivoServiciosPrestados',
            },
        ),
        migrations.CreateModel(
            name='ArchivoRetencion',
            fields=[
                ('are_id', models.AutoField(primary_key=True, serialize=False)),
                ('are_titulo', models.CharField(max_length=255)),
                ('are_descripcion', models.CharField(max_length=500)),
                ('are_direccion', models.CharField(max_length=500)),
                ('are_fecha_modif', models.DateTimeField()),
                ('are_estatus', models.BooleanField(default=True)),
                ('are_cli_fk', models.ForeignKey(blank=True, db_column='are_cli_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Cliente')),
                ('are_pro_fk', models.ForeignKey(blank=True, db_column='are_pro_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Proveedor')),
                ('are_usu_modif_fk', models.ForeignKey(blank=True, db_column='are_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArchivoRetencion',
            },
        ),
        migrations.CreateModel(
            name='ArchivoGestionCalidadEmpleado',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False)),
                ('ae_fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('ae_visto', models.BooleanField(default=True)),
                ('ae_fecha_modif', models.DateTimeField()),
                ('ae_estatus', models.BooleanField(default=True)),
                ('ae_agc_fk', models.ForeignKey(blank=True, db_column='ae_agc_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.ArchivoGestionCalidad')),
                ('ae_emp_fk', models.ForeignKey(blank=True, db_column='ae_emp_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Empleado')),
                ('ae_usu_modif_fk', models.ForeignKey(blank=True, db_column='ae_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArchivoGestionCalidad_Usuario',
                'unique_together': {('ae_emp_fk', 'ae_agc_fk')},
            },
        ),
        migrations.AddField(
            model_name='archivogestioncalidad',
            name='agc_empleados',
            field=models.ManyToManyField(through='user_login_api.ArchivoGestionCalidadEmpleado', to='user_login_api.Empleado'),
        ),
        migrations.AddField(
            model_name='archivogestioncalidad',
            name='agc_usu_modif_fk',
            field=models.ForeignKey(blank=True, db_column='agc_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='anu_empleados',
            field=models.ManyToManyField(through='user_login_api.EmpleadoAnuncio', to='user_login_api.Empleado'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='anu_usu_modif_fk',
            field=models.ForeignKey(blank=True, db_column='anu_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
