# Generated by Django 3.0 on 2021-10-10 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0005_auto_20211002_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoGestionCalidadDepartamento',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False)),
                ('ae_fecha_modif', models.DateTimeField()),
                ('ae_estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ArchivoGestionCalidad_Departamento',
            },
        ),
        migrations.RemoveField(
            model_name='archivogestioncalidad',
            name='agc_empleados',
        ),
        migrations.AlterField(
            model_name='archivogestioncalidad',
            name='agc_descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ArchivoGestionCalidadEmpleado',
        ),
        migrations.AddField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_agc_fk',
            field=models.ForeignKey(blank=True, db_column='ae_agc_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.ArchivoGestionCalidad'),
        ),
        migrations.AddField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_dep_fk',
            field=models.ForeignKey(blank=True, db_column='ae_dep_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Departamento'),
        ),
        migrations.AddField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_usu_modif_fk',
            field=models.ForeignKey(blank=True, db_column='ae_usu_modif_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivogestioncalidad',
            name='agc_departamentos',
            field=models.ManyToManyField(through='user_login_api.ArchivoGestionCalidadDepartamento', to='user_login_api.Departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='archivogestioncalidaddepartamento',
            unique_together={('ae_dep_fk', 'ae_agc_fk')},
        ),
    ]
