# Generated by Django 3.0 on 2021-10-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0007_archivogestioncalidad_agc_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usu_tipo',
            field=models.CharField(default='Empleado', max_length=250),
        ),
    ]
