# Generated by Django 3.0 on 2021-10-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0008_usuario_usu_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='emp_dep_fk',
            field=models.ForeignKey(db_column='emp_dep_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_rol_fk',
            field=models.ForeignKey(db_column='emp_rol_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol'),
        ),
    ]
