# Generated by Django 3.0 on 2021-10-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_api', '0009_auto_20211012_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='anu_usu_modif_fk',
            field=models.ForeignKey(db_column='anu_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivogestioncalidad',
            name='agc_usu_modif_fk',
            field=models.ForeignKey(db_column='agc_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_agc_fk',
            field=models.ForeignKey(db_column='ae_agc_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.ArchivoGestionCalidad'),
        ),
        migrations.AlterField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_dep_fk',
            field=models.ForeignKey(db_column='ae_dep_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Departamento'),
        ),
        migrations.AlterField(
            model_name='archivogestioncalidaddepartamento',
            name='ae_usu_modif_fk',
            field=models.ForeignKey(db_column='ae_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivoretencion',
            name='are_cli_fk',
            field=models.ForeignKey(db_column='are_cli_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Cliente'),
        ),
        migrations.AlterField(
            model_name='archivoretencion',
            name='are_pro_fk',
            field=models.ForeignKey(db_column='are_pro_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Proveedor'),
        ),
        migrations.AlterField(
            model_name='archivoretencion',
            name='are_usu_modif_fk',
            field=models.ForeignKey(db_column='are_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivoserviciosprestados',
            name='asp_pro_fk',
            field=models.ForeignKey(db_column='asp_pro_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Proveedor'),
        ),
        migrations.AlterField(
            model_name='archivoserviciosprestados',
            name='asp_usu_modif_fk',
            field=models.ForeignKey(db_column='asp_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_rol_fk',
            field=models.ForeignKey(db_column='cli_rol_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_usu_fk',
            field=models.ForeignKey(db_column='cli_usu_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cli_usu_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_usu_modif_fk',
            field=models.ForeignKey(db_column='cli_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cli_usu_modif_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='dep_usu_modif_fk',
            field=models.ForeignKey(db_column='dep_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_usu_fk',
            field=models.ForeignKey(db_column='emp_usu_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_usu_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_usu_modif_fk',
            field=models.ForeignKey(db_column='emp_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_usu_modif_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleadoanuncio',
            name='ea_anu_fk',
            field=models.ForeignKey(db_column='ea_anu_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Anuncio'),
        ),
        migrations.AlterField(
            model_name='empleadoanuncio',
            name='ea_emp_fk',
            field=models.ForeignKey(db_column='ea_emp_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Empleado'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='per_usu_modif_fk',
            field=models.ForeignKey(db_column='per_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pro_rol_fk',
            field=models.ForeignKey(db_column='pro_rol_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pro_usu_fk',
            field=models.ForeignKey(db_column='pro_usu_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_usu_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pro_usu_modif_fk',
            field=models.ForeignKey(db_column='pro_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_usu_modif_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_usu_modif_fk',
            field=models.ForeignKey(db_column='rol_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='rp_per_fk',
            field=models.ForeignKey(db_column='rp_per_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Permiso'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='rp_rol_fk',
            field=models.ForeignKey(db_column='rp_rol_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='user_login_api.Rol'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='rp_usu_modif_fk',
            field=models.ForeignKey(db_column='rp_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_usu_modif_fk',
            field=models.ForeignKey(db_column='usu_usu_modif_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usu_usu_modif_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
