# Generated by Django 3.0 on 2021-10-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_proveedor_api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoretencioniva',
            name='pagRetIva_doc_num_control',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
