# Generated by Django 3.0 on 2021-10-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_proveedor_api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_fecha_inac',
            field=models.DateField(null=True),
        ),
    ]
