# Generated by Django 3.0 on 2021-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_proveedor_api_rest', '0002_auto_20211013_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_num_control',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
