# Generated by Django 3.0 on 2021-10-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_proveedor_api_rest', '0004_auto_20211013_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventarenglon',
            name='facren_costo_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facturaventarenglon',
            name='facren_monto_imp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facturaventarenglon',
            name='facren_precio_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facturaventarenglon',
            name='facren_reng_neto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facturaventarenglon',
            name='facren_total_art',
            field=models.FloatField(),
        ),
    ]
