# Generated by Django 3.0 on 2021-10-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_proveedor_api_rest', '0005_auto_20211013_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventarenglon',
            name='facren_costo_unit',
        ),
    ]
